apiVersion: batch/v1
kind: Job
metadata:
  name: test-job2
  labels:
    app: test-job
spec:
  template:
    metadata:
      name: test-job
      labels:
        app: test-job
    spec:
      restartPolicy: Never
      containers:
      - name: insert
        env:
          - name: DATABASE_URI
            value: postgres
        image: postgres:11
        command:
          - sh
          - "-c"
          - |
            PGPASSWORD=passwd psql2 -d myapp -U myuser -h $DATABASE_URI  <<'EOF'
              INSERT INTO client(id,name) 
              VALUES(DEFAULT,'John');
            EOF
  backoffLimit: 0 #number of retries before considering a Job as failed
