name: CI

on:
  pull_request:

jobs:
  validate-manifests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: azure/setup-kubectl@v3
        with:
          version: 'latest'
      - name: Run manifest validation
        run: ./tests/test_manifests.sh
